# Generated by Django 3.0.6 on 2020-05-14 16:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(help_text="article tag", max_length=255), null=True, size=None
            ),
        ),
    ]
